import { Stage, SectionDef } from './types';

export const STAGES: Stage[] = [
  { key: 'inquiry', label: 'Inquiry', code: '01', prob: 0.10, heat: '#4f6d7a', blurb: 'New contact in.' },
  { key: 'consult', label: 'Consultation', code: '02', prob: 0.25, heat: '#6a8079', blurb: 'Discovery / design call.' },
  { key: 'design', label: 'Design Locked', code: '03', prob: 0.50, heat: '#998a5f', blurb: 'Model, finishes & scope finalized.' },
  { key: 'proposal', label: 'Proposal Sent', code: '04', prob: 0.65, heat: '#c0823f', blurb: 'Estimate + brochure + build plan out.' },
  { key: 'deposit', label: 'Hold Deposit', code: '05', prob: 0.85, heat: '#d96a2b', blurb: '$450 deposit — production slot locked.' },
  { key: 'production', label: 'In Production', code: '06', prob: 0.95, heat: '#e85a23', blurb: '80% down — building (12-wk lead).' },
  { key: 'complete', label: 'Completed', code: '07', prob: 1.00, heat: '#ff4d12', blurb: 'Installed · 20% balance · sign-off.' },
];

export const HEALTH: Record<string, { c: string; label: string }> = {
  hot: { c: '#e85a23', label: 'Hot' },
  warm: { c: '#d8a24a', label: 'Warm' },
  cold: { c: '#5b7a8c', label: 'Cold' },
};

export const INCLUDE_KEYS: [string, string][] = [
  ['sitePlan', 'Site plan'],
  ['structural', 'Structural'],
  ['anchorage', 'Anchorage'],
  ['utilities', 'Utilities'],
  ['elevations', 'Elevations'],
];

export const RES_TYPES = ['Brochure', 'Pricing sheet', 'Google Sheet', 'Spec sheet', 'Link'];
export const LIB_TYPES = ['Folder', 'Brochure', 'Pricing', 'Google Sheet', 'Doc', 'Link'];
export const DOC_TYPES = ['Plan Set', 'Proposal', 'Site Photos', 'Contract', 'Other'];
export const COMM_CHANNELS = ['Call', 'Email', 'Text', 'Meeting', 'Note'];

export const SECTIONS: SectionDef[] = [
  {
    id: 'suppliers', label: 'Suppliers', title: 'Suppliers',
    desc: 'Build partners and material suppliers — with one-tap contact.',
    lede: 'Everyone in the supply chain, contactable in one tap.',
    titleField: 'name', icon: 'truck',
    fields: [
      { key: 'name', label: 'Supplier / partner', type: 'text', req: true },
      { key: 'role', label: 'Role', type: 'select', opts: ['Build partner', 'Material supplier', 'Install partner', 'Logistics', 'Other'] },
      { key: 'status', label: 'Status', type: 'select', opts: ['Preferred', 'Backup', 'Trial'] },
      { key: 'category', label: 'Supplies / scope', type: 'text', ph: 'Heaters & sauna components' },
      { key: 'contactName', label: 'Contact name', type: 'text', ph: 'Sadie Stayner' },
      { key: 'email', label: 'Email', type: 'text', mono: true, ph: 'name@vendor.com' },
      { key: 'phone', label: 'Phone', type: 'text', mono: true, ph: '801-555-0100' },
      { key: 'website', label: 'Website', type: 'text', mono: true, ph: 'https://…' },
      { key: 'leadTime', label: 'Lead time', type: 'text', mono: true, ph: '5–6 wks' },
      { key: 'supplyType', label: 'Supply responsibility', type: 'select', opts: ['', 'NP-supplied', 'Partner-sourced'] },
      { key: 'supplies', label: 'Details', type: 'textarea', ph: 'Specific products, terms, anything the team needs.' },
      { key: 'notes', label: 'Notes', type: 'textarea', ph: 'Address, account terms, flags.' },
    ],
  },
  {
    id: 'products', label: 'Products', title: 'Products',
    desc: 'Each NP unit — specs, revs, and attached resources.',
    lede: 'The model line as it stands today, with brochures and sheets attached.',
    titleField: 'name', icon: 'box',
    fields: [
      { key: 'name', label: 'Product name', type: 'text', req: true, ph: 'Refuge 2 — 2-Person Cabin Sauna' },
      { key: 'rev', label: 'Revision', type: 'text', mono: true, ph: 'Rev C' },
      { key: 'status', label: 'Status', type: 'select', opts: ['Active', 'In design', 'Retired'] },
      { key: 'dimensions', label: 'Dimensions', type: 'text', mono: true, ph: "6'x4'x7' (84\" H)" },
      { key: 'priceBand', label: 'Price band', type: 'text', mono: true, ph: '$24k–$28k' },
      { key: 'leadTime', label: 'Lead time', type: 'text', mono: true, ph: '8–10 wks' },
      { key: 'finishes', label: 'Finishes', type: 'text', ph: 'Thermo-cedar ext / clear cedar int' },
      { key: 'specs', label: 'Key specs', type: 'textarea', ph: 'HUUM Drop 6kW · 1 bench tier · single glass door' },
      { key: 'brochures', label: 'Brochures & sales resources', type: 'reslist', addLabel: 'brochure / sheet' },
    ],
  },
  {
    id: 'research', label: 'Research', title: 'Research',
    desc: 'Material tests, code findings, and market notes.',
    lede: 'What we have learned, so a question is answered once and never re-litigated.',
    titleField: 'title', icon: 'flask',
    fields: [
      { key: 'title', label: 'Title', type: 'text', req: true, ph: 'Summit County exempt-structure threshold' },
      { key: 'type', label: 'Type', type: 'select', opts: ['Code finding', 'Material test', 'Market', 'Competitor'] },
      { key: 'jurisdiction', label: 'Jurisdiction (if code)', type: 'text', ph: 'Summit County' },
      { key: 'summary', label: 'Finding', type: 'textarea', req: true, ph: 'What we learned and what it changes.' },
      { key: 'owner', label: 'Owner', type: 'text', ph: 'Cole' },
      { key: 'date', label: 'Date', type: 'text', mono: true, ph: '2026-05-10' },
      { key: 'link', label: 'Source link', type: 'text', ph: 'https://…' },
    ],
  },
  {
    id: 'improvements', label: 'Improvements', title: 'Product Improvements',
    desc: 'The change log + backlog: proposed through shipped.',
    lede: 'Every idea to make the product better — tracked from proposed to shipped.',
    titleField: 'title', icon: 'trending-up',
    fields: [
      { key: 'title', label: 'Improvement', type: 'text', req: true, ph: 'Move heater control to exterior junction' },
      { key: 'product', label: 'Affects', type: 'text', ph: 'Refuge 2 · Rev C→D' },
      { key: 'status', label: 'Status', type: 'select', opts: ['Proposed', 'In progress', 'Shipped', 'Parked'] },
      { key: 'impact', label: 'Impact', type: 'textarea', ph: 'Cuts install time ~45 min; cleaner interior' },
      { key: 'owner', label: 'Owner', type: 'text', ph: 'Cole' },
      { key: 'date', label: 'Logged', type: 'text', mono: true, ph: '2026-06-01' },
    ],
  },
  {
    id: 'plans', label: 'Build Plans', title: 'Build Plan Sets',
    desc: 'Plan set per product — version, specs, and cut list.',
    lede: 'The catalog of issued plan sets. Each one prints to a clean build sheet.',
    titleField: 'name', icon: 'file-text',
    fields: [
      { key: 'name', label: 'Plan set name', type: 'text', req: true, ph: 'Refuge 2 — Plan Set' },
      { key: 'product', label: 'Product / rev', type: 'text', ph: 'Refuge 2 (Rev C)' },
      { key: 'version', label: 'Version', type: 'text', mono: true, ph: 'v1.3' },
      { key: 'date', label: 'Date', type: 'text', mono: true, ph: '2026-06-12' },
      { key: 'status', label: 'Status', type: 'select', opts: ['Draft', 'Issued', 'Superseded'] },
      { key: 'includes', label: 'Set includes', type: 'includes' },
      { key: 'specs', label: 'Build specs', type: 'textarea', ph: "Footprint 6'x4'; 84\" ridge; 4x helical anchors" },
      { key: 'cuts', label: 'Cut list', type: 'textarea', mono: true, ph: 'Wall studs 2x4 @16" — qty 24 @ 81"' },
      { key: 'notes', label: 'Field notes', type: 'text', ph: 'Verify anchor torque 150 ft-lb' },
      { key: 'pdfLink', label: 'PDF link', type: 'text', ph: 'Drive / link to full set' },
    ],
  },
  {
    id: 'resources', label: 'Resources', title: 'Sales Resources',
    desc: 'Every sales resource in one place — catalogs, brochures, pricing.',
    lede: 'One home for the resources you reach for on a sales call.',
    titleField: 'label', icon: 'folder',
    fields: [
      { key: 'label', label: 'Name', type: 'text', req: true, ph: 'Product Brochures' },
      { key: 'type', label: 'Type', type: 'select', opts: ['Folder', 'Brochure', 'Pricing', 'Google Sheet', 'Doc', 'Link'] },
      { key: 'url', label: 'Link', type: 'text', mono: true, ph: 'https://drive.google.com/…' },
      { key: 'note', label: 'Note', type: 'text', ph: 'What is in here' },
    ],
  },
  // ── Marketing Workspace ──
  {
    id: 'campaigns', label: 'Campaigns', title: 'Marketing Campaigns',
    desc: 'Every campaign tracked from planning through results.',
    lede: 'Plan it, run it, measure it. Every campaign in one place with budget, channel, and results.',
    titleField: 'name', icon: 'megaphone',
    fields: [
      { key: 'name', label: 'Campaign name', type: 'text', req: true, ph: 'Summer Sauna Launch — Instagram' },
      { key: 'type', label: 'Type', type: 'select', opts: ['Brand awareness', 'Lead gen', 'Retargeting', 'Email drip', 'Referral', 'Event promo', 'Partnership'] },
      { key: 'status', label: 'Status', type: 'select', opts: ['Planning', 'Active', 'Paused', 'Completed', 'Cancelled'] },
      { key: 'channel', label: 'Channel', type: 'select', opts: ['Instagram', 'Facebook', 'Google Ads', 'Email', 'Direct mail', 'In-person', 'YouTube', 'TikTok', 'LinkedIn', 'Multi-channel'] },
      { key: 'startDate', label: 'Start date', type: 'text', mono: true, ph: '2026-06-01' },
      { key: 'endDate', label: 'End date', type: 'text', mono: true, ph: '2026-07-31' },
      { key: 'budget', label: 'Budget', type: 'text', mono: true, ph: '$2,500' },
      { key: 'audience', label: 'Target audience', type: 'text', ph: 'Homeowners, Park City / Aspen, $500k+ home' },
      { key: 'goal', label: 'Goal / KPI', type: 'text', ph: '50 qualified leads, 3% conversion' },
      { key: 'results', label: 'Results', type: 'textarea', ph: 'Impressions, clicks, leads, conversions…' },
      { key: 'link', label: 'Campaign link', type: 'text', ph: 'https://…' },
      { key: 'notes', label: 'Notes', type: 'textarea', ph: 'Creative assets, learnings, next iteration.' },
    ],
  },
  {
    id: 'events', label: 'Events', title: 'Events',
    desc: 'Trade shows, open houses, install showcases — everything in-person.',
    lede: 'Every event on the calendar — from trade shows to backyard install showcases.',
    titleField: 'name', icon: 'calendar-event',
    fields: [
      { key: 'name', label: 'Event name', type: 'text', req: true, ph: 'Park City Home Show 2026' },
      { key: 'type', label: 'Type', type: 'select', opts: ['Trade show', 'Open house', 'Install showcase', 'Networking', 'Sponsorship', 'Workshop', 'Other'] },
      { key: 'date', label: 'Date', type: 'text', mono: true, ph: '2026-08-15' },
      { key: 'location', label: 'Location', type: 'text', ph: 'Park City Convention Center' },
      { key: 'status', label: 'Status', type: 'select', opts: ['Upcoming', 'Confirmed', 'In progress', 'Completed', 'Cancelled'] },
      { key: 'audience', label: 'Expected audience', type: 'text', ph: '500+ homeowners, architects, builders' },
      { key: 'cost', label: 'Cost / budget', type: 'text', mono: true, ph: '$1,200 booth + $300 materials' },
      { key: 'leads', label: 'Leads captured', type: 'text', mono: true, ph: '12 qualified' },
      { key: 'notes', label: 'Notes', type: 'textarea', ph: 'What to bring, who to talk to, follow-up plan.' },
      { key: 'link', label: 'Event link', type: 'text', ph: 'https://…' },
    ],
  },
  {
    id: 'content', label: 'Content', title: 'Content Calendar',
    desc: 'Blog posts, social media, videos — plan and track it all.',
    lede: 'The content pipeline. Plan, create, publish, and track what is working.',
    titleField: 'title', icon: 'pen-tool',
    fields: [
      { key: 'title', label: 'Title', type: 'text', req: true, ph: 'Why Thermo-Cedar Outlasts Everything' },
      { key: 'type', label: 'Type', type: 'select', opts: ['Blog post', 'Instagram post', 'Reel / video', 'Email newsletter', 'Case study', 'Photo shoot', 'Testimonial video', 'Other'] },
      { key: 'status', label: 'Status', type: 'select', opts: ['Idea', 'Drafting', 'Review', 'Scheduled', 'Published', 'Archived'] },
      { key: 'channel', label: 'Channel', type: 'select', opts: ['Website', 'Instagram', 'Facebook', 'YouTube', 'TikTok', 'Email', 'LinkedIn', 'Multi'] },
      { key: 'publishDate', label: 'Publish date', type: 'text', mono: true, ph: '2026-07-01' },
      { key: 'author', label: 'Author / creator', type: 'text', ph: 'Cole' },
      { key: 'topic', label: 'Topic / angle', type: 'text', ph: 'Material science, behind-the-build' },
      { key: 'url', label: 'Published URL', type: 'text', mono: true, ph: 'https://…' },
      { key: 'notes', label: 'Notes', type: 'textarea', ph: 'Draft notes, shot list, copy.' },
    ],
  },
  {
    id: 'testimonials', label: 'Testimonials', title: 'Testimonials',
    desc: 'Client quotes, reviews, and social proof — ready for any pitch.',
    lede: 'The proof. Every client quote, review, and case study organized and ready to deploy.',
    titleField: 'name', icon: 'quote',
    fields: [
      { key: 'name', label: 'Client name', type: 'text', req: true, ph: 'Andy Gunion' },
      { key: 'project', label: 'Project / product', type: 'text', ph: 'Refuge 2 — Aspen install' },
      { key: 'type', label: 'Type', type: 'select', opts: ['Written quote', 'Video testimonial', 'Google review', 'Social post', 'Case study', 'Referral'] },
      { key: 'quote', label: 'Quote / summary', type: 'textarea', req: true, ph: 'The full testimonial or key quote.' },
      { key: 'rating', label: 'Rating', type: 'select', opts: ['', '5 stars', '4 stars', '3 stars'] },
      { key: 'date', label: 'Date', type: 'text', mono: true, ph: '2026-06-15' },
      { key: 'source', label: 'Source', type: 'text', ph: 'Google, Instagram DM, email' },
      { key: 'approved', label: 'Approved for use', type: 'select', opts: ['Yes', 'Pending', 'No'] },
      { key: 'link', label: 'Link', type: 'text', ph: 'https://…' },
    ],
  },
  {
    id: 'webPresence', label: 'Web & Social', title: 'Web & Social Presence',
    desc: 'Every website, social account, and listing — with status.',
    lede: 'Your digital footprint in one view. Links, logins, and status for every platform.',
    titleField: 'label', icon: 'globe',
    fields: [
      { key: 'label', label: 'Name', type: 'text', req: true, ph: 'New Primitive — Instagram' },
      { key: 'platform', label: 'Platform', type: 'select', opts: ['Website', 'Instagram', 'Facebook', 'Google Business', 'YouTube', 'TikTok', 'LinkedIn', 'Yelp', 'Houzz', 'Pinterest', 'Other'] },
      { key: 'url', label: 'URL', type: 'text', mono: true, ph: 'https://instagram.com/newprimitive' },
      { key: 'handle', label: 'Handle / username', type: 'text', mono: true, ph: '@newprimitive' },
      { key: 'status', label: 'Status', type: 'select', opts: ['Active', 'Inactive', 'Setup needed', 'Paused'] },
      { key: 'notes', label: 'Notes', type: 'text', ph: 'Login info location, posting cadence, etc.' },
    ],
  },
  // ── Projects Workspace ──
  {
    id: 'projects', label: 'Projects', title: 'Active Projects',
    desc: 'Every install and job — from deposit through sign-off.',
    lede: 'The build board. Every active job with site status, timelines, and partner handoff tracking.',
    titleField: 'name', icon: 'hard-hat',
    fields: [
      { key: 'name', label: 'Project name', type: 'text', req: true, ph: 'Gunion — Aspen Thermal Suite' },
      { key: 'client', label: 'Client', type: 'text', ph: 'Andy Gunion' },
      { key: 'type', label: 'Type', type: 'select', opts: ['Residential', 'Commercial', 'Multi-unit'] },
      { key: 'location', label: 'Location', type: 'text', ph: '1780 Juniper, Aspen, CO' },
      { key: 'product', label: 'Product', type: 'text', ph: 'Thermal Suite Essential MP1' },
      { key: 'status', label: 'Status', type: 'select', opts: ['Pre-build', 'Site prep', 'In fabrication', 'Shipping', 'On-site install', 'Punch list', 'Complete', 'On hold'] },
      { key: 'startDate', label: 'Start date', type: 'text', mono: true, ph: '2026-07-01' },
      { key: 'targetComplete', label: 'Target completion', type: 'text', mono: true, ph: '2026-09-15' },
      { key: 'siteStatus', label: 'Site readiness', type: 'select', opts: ['Not started', 'Pad poured', 'Electrical run', 'Plumbing run', 'Ready for set', 'Complete'] },
      { key: 'buildPartner', label: 'Build partner', type: 'text', ph: 'Qontrast' },
      { key: 'value', label: 'Contract value', type: 'text', mono: true, ph: '$66,000' },
      { key: 'depositPaid', label: 'Deposit paid', type: 'select', opts: ['', 'Yes', 'No', 'Partial'] },
      { key: 'balanceDue', label: 'Balance due', type: 'text', mono: true, ph: '$13,200' },
      { key: 'permitStatus', label: 'Permit status', type: 'select', opts: ['', 'Not required', 'Applied', 'Approved', 'Denied', 'Exempt'] },
      { key: 'electricalStatus', label: 'Electrical', type: 'select', opts: ['', 'Not started', 'Scheduled', 'Roughed in', 'Final', 'Complete'] },
      { key: 'craneDate', label: 'Crane / delivery date', type: 'text', mono: true, ph: '2026-09-10' },
      { key: 'notes', label: 'Notes', type: 'textarea', ph: 'Site access, special instructions, open items.' },
    ],
  },
  // ── Customers Workspace ──
  {
    id: 'customers', label: 'Customers', title: 'Customers',
    desc: 'Post-sale relationships — warranty, referrals, satisfaction.',
    lede: 'Every completed client. Track warranties, gather referrals, and stay connected.',
    titleField: 'name', icon: 'users',
    fields: [
      { key: 'name', label: 'Name', type: 'text', req: true, ph: 'Andy & Sarah Gunion' },
      { key: 'email', label: 'Email', type: 'text', mono: true, ph: 'andy@example.com' },
      { key: 'phone', label: 'Phone', type: 'text', mono: true, ph: '970-376-2116' },
      { key: 'type', label: 'Type', type: 'select', opts: ['Residential', 'Commercial', 'Multi-unit'] },
      { key: 'location', label: 'Location', type: 'text', ph: 'Aspen, CO' },
      { key: 'product', label: 'Product installed', type: 'text', ph: 'Thermal Suite Essential MP1' },
      { key: 'installDate', label: 'Install date', type: 'text', mono: true, ph: '2026-09-15' },
      { key: 'warrantyExpires', label: 'Warranty expires', type: 'text', mono: true, ph: '2028-09-15' },
      { key: 'satisfaction', label: 'Satisfaction', type: 'select', opts: ['Thrilled', 'Happy', 'Neutral', 'Issue open'] },
      { key: 'referralSource', label: 'How they found us', type: 'text', ph: 'Instagram, referral from…' },
      { key: 'referralsGiven', label: 'Referrals given', type: 'text', mono: true, ph: '2' },
      { key: 'testimonial', label: 'Testimonial status', type: 'select', opts: ['', 'Requested', 'Received', 'Published'] },
      { key: 'notes', label: 'Notes', type: 'textarea', ph: 'Follow-up schedule, warranty issues, referral notes.' },
    ],
  },
  // ── Finance Workspace ──
  {
    id: 'finance', label: 'Finance', title: 'Finance Tracker',
    desc: 'Estimates, invoices, expenses — with job-level margin tracking.',
    lede: 'Revenue and costs at a glance. Every transaction tied to a job for real margin visibility.',
    titleField: 'label', icon: 'dollar',
    fields: [
      { key: 'label', label: 'Description', type: 'text', req: true, ph: 'Gunion — 80% production deposit' },
      { key: 'type', label: 'Type', type: 'select', opts: ['Revenue', 'Expense', 'Estimate', 'Invoice', 'Deposit', 'Refund'] },
      { key: 'category', label: 'Category', type: 'select', opts: ['Materials', 'Labor', 'Subcontractor', 'Shipping', 'Marketing', 'Overhead', 'Permits', 'Equipment', 'Client payment', 'Other'] },
      { key: 'amount', label: 'Amount', type: 'text', mono: true, req: true, ph: '$52,800' },
      { key: 'date', label: 'Date', type: 'text', mono: true, ph: '2026-07-01' },
      { key: 'status', label: 'Status', type: 'select', opts: ['Draft', 'Sent', 'Paid', 'Overdue', 'Partial', 'Void'] },
      { key: 'job', label: 'Job / project', type: 'text', ph: 'Gunion — Aspen' },
      { key: 'vendor', label: 'Vendor / client', type: 'text', ph: 'Qontrast · Superior Saunas' },
      { key: 'invoice', label: 'Invoice #', type: 'text', mono: true, ph: 'INV-2026-042' },
      { key: 'qbRef', label: 'QuickBooks ref', type: 'text', mono: true, ph: 'QBO-1234' },
      { key: 'notes', label: 'Notes', type: 'textarea', ph: 'Payment terms, receipt link, flags.' },
    ],
  },
];

export const STATUS_COLORS: Record<string, string> = {
  Preferred: 'ok', Active: 'ok', Issued: 'ok', Shipped: 'ok', Completed: 'ok', Published: 'ok', Paid: 'ok',
  Thrilled: 'ok', Happy: 'ok', Received: 'ok', Approved: 'ok', 'Ready for set': 'ok', Complete: 'ok',
  'In progress': 'warn', 'In design': 'warn', Draft: 'warn', Proposed: 'ember', Planning: 'warn',
  Drafting: 'warn', Review: 'warn', Scheduled: 'warn', Upcoming: 'warn', Confirmed: 'warn',
  'Pre-build': 'warn', 'Site prep': 'warn', 'In fabrication': 'warn', Sent: 'warn', Partial: 'warn',
  Pending: 'warn', 'Applied': 'warn', Requested: 'warn',
  'Lead gen': 'ember', 'Brand awareness': 'ember', Overdue: 'ember', 'Issue open': 'ember',
  Backup: 'mute', Trial: 'mute', Retired: 'mute', Parked: 'mute', Superseded: 'mute',
  Cancelled: 'mute', Paused: 'mute', Inactive: 'mute', Archived: 'mute', Void: 'mute',
  'On hold': 'mute', Neutral: 'mute', Idea: 'mute', 'Setup needed': 'mute',
  'Not required': 'mute', Exempt: 'mute', Denied: 'mute',
};

export const ROLE_COLORS: Record<string, string> = {
  'Build partner': 'ember', 'Material supplier': 'ok', 'Install partner': 'mute', 'Logistics': 'mute',
};
